### PR TITLE
Allow newer versions of duckdb

### PR DESCRIPTION
**Pull request by JorgeGarciaIrazabal**
Duckdb 0.7.1 has a lot of bug fixes and interesting features like support for filesystems: https://duckdb.org/docs/guides/python/filesystems

Removing duckdb pin from 0.6.1 to 0.6.1-0.8.0. Is there any concern with this change?

### CODE REVIEW

**Comment by vijaykiran** [comment]
@JorgeGarciaIrazabal  thanks for the PR - I think we had some issues with latest duckdb - we will review and check the tests and upgrade it.

**Comment by JorgeGarciaIrazabal** [comment]
> @JorgeGarciaIrazabal thanks for the PR - I think we had some issues with latest duckdb - we will review and check the tests and upgrade it.

thank you

**Comment by vijaykiran** [comment]
@JorgeGarciaIrazabal  thanks a lot for the PR - merged it via https://github.com/sodadata/soda-core/commit/dcb66f4d6d989a5124da10cc50e3ae3201795278 

We will release a new tag today with the fix.

**Comment by JorgeGarciaIrazabal** [comment]
> We will release a new tag today with the fix.

@vijaykiran  just following up, any updates on the release?

**Comment by vijaykiran** [comment]
@JorgeGarciaIrazabal 3.0.38 has been tagged with the fix. Can you check?

**Comment by JorgeGarciaIrazabal** [comment]
@vijaykiran I didn't see in the releases in github but it is in pypi. This works for us, thank you very much!

**Pull request closed without merging**
