### PR TITLE
duckdb support (experimental)

### PR DESCRIPTION
**Pull request by vijaykiran**

### CODE REVIEW

**Comment by geertjan-garvis** [comment]
@vijaykiran , thanks, will take a look shortly at the statistical tests i see failing in CI. didn't see these on my local.

**Comment by vijaykiran** [comment]
Please use this branch to create a PR - so I can consolidate everything

**Comment by vijaykiran** [comment]
> @vijaykiran , thanks, will take a look shortly at the statistical tests i see failing in CI. didn't see these on my local.

@geertjan-garvis  Please use this branch to create a PR - so I can consolidate everything

**Comment by vijaykiran** [comment]
@geertjan-garvis  I fixed it :) will merge it when everything is green.

**Pull request merged**
