### PR TITLE
SODA-944 Enable Snowflake Tokens

### PR DESCRIPTION
**Pull request by Adamage**
Issue: #1471

### CODE REVIEW

**Comment by Adamage** [comment]
@vijaykiran  Hello. I would like to contribute to this repository.

**Comment by Adamage** [comment]
@vijaykiran  I did repeat unit tests locally and I dont have the failures from CI system.
```
 tox -- soda -k soda
```

```
 2 failed, 203 passed, 12 skipped, 26 warnings, 1 error in 24.08s
```

```
collected 218 items

soda/athena/tests/test_athena.py .                                                                                                                                   [  0%]
soda/bigquery/tests/test_bigquery.py .                                                                                                                               [  0%]
soda/core/tests/cli/test_cli_return_values.py ....                                                                                                                   [  2%]
soda/core/tests/cli/test_cli_scan.py ..                                                                                                                              [  3%]
soda/core/tests/cli/test_cli_update_distribution_file.py .                                                                                                           [  4%]
soda/core/tests/data_source/test_anomaly_check.py ...ss.......                                                                                                       [  9%]
soda/core/tests/data_source/test_automated_monitoring.py .                                                                                                           [ 10%]
soda/core/tests/data_source/test_bug_double_metric_computation.py .                                                                                                  [ 10%]
soda/core/tests/data_source/test_case_sensitive_names.py .                                                                                                           [ 11%]
soda/core/tests/data_source/test_change_over_time.py .                                                                                                               [ 11%]
soda/core/tests/data_source/test_check_identity.py ....                                                                                                              [ 13%]
soda/core/tests/data_source/test_count.py ..                                                                                                                         [ 14%]
soda/core/tests/data_source/test_data_source_specific_aggregation_functions.py .                                                                                     [ 14%]
soda/core/tests/data_source/test_discover_tables.py ...                                                                                                              [ 16%]
soda/core/tests/data_source/test_distribution_check.py .....                                                                                                         [ 18%]
soda/core/tests/data_source/test_duplicates.py ..                                                                                                                    [ 19%]
soda/core/tests/data_source/test_for_each_dataset.py ....                                                                                                            [ 21%]
soda/core/tests/data_source/test_formats.py .                                                                                                                        [ 21%]
soda/core/tests/data_source/test_freshness.py .........                                                                                                              [ 25%]
soda/core/tests/data_source/test_invalid.py .......                                                                                                                  [ 28%]
soda/core/tests/data_source/test_invalid_data_source_type.py .                                                                                                       [ 29%]
soda/core/tests/data_source/test_metric_check_filter.py ....                                                                                                         [ 31%]
soda/core/tests/data_source/test_metric_identity.py ..                                                                                                               [ 32%]
soda/core/tests/data_source/test_min_max_avg_length.py .                                                                                                             [ 32%]
soda/core/tests/data_source/test_min_max_avg_sum.py .                                                                                                                [ 33%]
soda/core/tests/data_source/test_missing.py ....                                                                                                                     [ 34%]
soda/core/tests/data_source/test_numerical_metric_checks_on_text_columns.py ..                                                                                       [ 35%]
soda/core/tests/data_source/test_percentage_metrics.py .                                                                                                             [ 36%]
soda/core/tests/data_source/test_profile_columns.py ..s.....                                                                                                         [ 39%]
soda/core/tests/data_source/test_queries_metadata.py ssss                                                                                                            [ 41%]
soda/core/tests/data_source/test_queries_table_filter.py ssss                                                                                                        [ 43%]
soda/core/tests/data_source/test_reference_check.py ...                                                                                                              [ 44%]
soda/core/tests/data_source/test_row_count_comparison.py ..                                                                                                          [ 45%]
soda/core/tests/data_source/test_sample_tables.py ...                                                                                                                [ 47%]
soda/core/tests/data_source/test_samples.py ......                                                                                                                   [ 50%]
soda/core/tests/data_source/test_schema_changes.py .....                                                                                                             [ 52%]
soda/core/tests/data_source/test_schema_column_types.py ...                                                                                                          [ 53%]
soda/core/tests/data_source/test_schema_forbidden_columns.py ....                                                                                                    [ 55%]
soda/core/tests/data_source/test_schema_index.py ...                                                                                                                 [ 56%]
soda/core/tests/data_source/test_schema_required_columns.py ...                                                                                                      [ 58%]
soda/core/tests/data_source/test_table_filter.py ..                                                                                                                  [ 59%]
soda/core/tests/data_source/test_user_defined_failed_rows_checks.py .......                                                                                          [ 62%]
soda/core/tests/data_source/test_user_defined_metric_checks.py ..                                                                                                    [ 63%]
soda/core/tests/data_source/test_warning_threshold.py .                                                                                                              [ 63%]
soda/core/tests/integration/test_samples_integration.py s                                                                                                            [ 64%]
soda/core/tests/unit/test_checks_yaml_parser.py ....                                                                                                                 [ 66%]
soda/core/tests/unit/test_collect_files.py ....                                                                                                                      [ 67%]
soda/core/tests/unit/test_configuration_yaml_parser.py ...                                                                                                           [ 69%]
soda/core/tests/unit/test_data_source_validation.py ..                                                                                                               [ 70%]
soda/core/tests/unit/test_docs_link.py .                                                                                                                             [ 70%]
soda/core/tests/unit/test_sodacl_error_no_threshold.py .                                                                                                             [ 71%]
soda/core/tests/unit/test_sodacl_error_user_defined_queries.py ...                                                                                                   [ 72%]
soda/core/tests/unit/test_telemetry.py ......                                                                                                                        [ 75%]
soda/core/tests/unit/test_variables.py .                                                                                                                             [ 75%]
soda/postgres/tests/test_postgres_connection_validation.py .                                                                                                         [ 76%]
soda/postgres/tests/test_postgres_specific_stuff.py E                                                                                                                [ 76%]
soda/redshift/tests/test_redshift.py .                                                                                                                               [ 77%]
soda/scientific/tests/distribution_comparison_test.py ............................................                                                                   [ 97%]
soda/scientific/tests/generate_dro_test.py ..                                                                                                                        [ 98%]
soda/scientific/tests/anomaly_detection/anomaly_detector_test.py .                                                                                                   [ 98%]
soda/snowflake/tests/test_snowflake.py .                                                                                                                             [ 99%]
soda/spark/tests/test_table_name_filtering.py F                                                                                                                      [ 99%]
soda/spark_df/tests/test_spark_df.py F                                                                                                                               [100%]
```

**Comment by vijaykiran** [comment]
@Adamage thank you for the PR!  I think CI needs secrets access. I'll pull in as a branch and merge it.

**Comment by Adamage** [comment]
> @Adamage thank you for the PR! I think CI needs secrets access. I'll pull in as a branch and merge it.

Thanks for the extra mile and putting another PR up. Should I close this now?

**Comment by vijaykiran** [comment]
Merged via https://github.com/sodadata/soda-core/pull/1480

**Comment by vijaykiran** [comment]
@Adamage  No problem - it is merged :)

**Pull request closed without merging**
